name: CI/CD Pipeline

on:
  push:
    branches:
      - main # or master, depending on your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Clean and Run Docker Compose services (for testing)
        run: |
          docker compose down -v || true # Ensure clean slate, ignore errors if containers don't exist
          docker compose up -d

      - name: Wait for services to be ready
        run: |
          for i in $(seq 1 30); do
            curl -f http://localhost:8000/status && break
            echo "Waiting for service to be ready... ($i/30)"
            sleep 2
          done
          curl -f http://localhost:8000/status || { echo "Service not ready after 60 seconds!"; exit 1; }

      - name: Run tests
        run: curl http://localhost:8000/status

      - name: Stop Docker Compose services
        if: always() # Run even if previous steps fail
        run: docker compose down
